In [3]:
import pandas as pd
import numpy as np

In [4]:
np.random.seed(101)
# cria valores aleatorios universais, que podem ser vistos igualmente

In [5]:
df = pd.DataFrame(np.random.randn(5,4), index = ' A B C D E'.split(), columns = 'W X Y Z'.split())
# faz um dataframe(tabela), com numeros sorteados usando rand n de 5 linhas e 4 colunas, o spli() separa pelos espaços as letras para assim coloca-las nas linhas e nas colunas

In [6]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [7]:
df['new'] = df['W'] + df['X']
# soma as colunas w e x e coloca elas em uma nova coluna no dataframe

In [8]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [9]:
df.drop('new', axis= 1)
# exclui a coluna new, o axis selecio a coluna por conta do 1, se for 0 e o indice de linha

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [10]:
df
# nao atribuiu ao dataframe original o drop

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [11]:
df.drop('new', axis= 1, inplace=True)
# utilizando o parametro inplace a alteração sera feita direto no dataframe

In [12]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df.loc['A', 'W']
# localiza no df a coluna a linha A e a coluna B

np.float64(2.706849839399938)

In [ ]:
df.loc['A']
# tendo so o a linha como parametro retorna todas as colunas

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [19]:
df.iloc[3:4, :2]

          W         X
D  0.188695 -0.758872