In [31]:
import pandas as pd
import numpy as np

In [32]:
np.random.seed(101)
# gera valores aleatorios entre 0 e 100, o seed faz com que os valores sejam semppre os mesmos caso use o mesmo seed

In [33]:
paises=['BRASIL','ALEMANHA','FRANÇA','ESPANHA','ARGENTINA']
anos =[2002,2020, 2019,2006]

In [34]:
df = pd.DataFrame(np.random.rand(5,4), index = paises, columns = anos)
# faz um dataframe com as lista (tabela)

In [35]:
df

               2002      2020      2019      2006
BRASIL     0.516399  0.570668  0.028474  0.171522
ALEMANHA   0.685277  0.833897  0.306966  0.893613
FRANÇA     0.721544  0.189939  0.554228  0.352132
ESPANHA    0.181892  0.785602  0.965483  0.232354
ARGENTINA  0.083561  0.603548  0.728993  0.276239

In [36]:
df['nnt'] = df[2002] + df[2006]
# soma os anos 2002 e 2006 e coloca elas em uma nova coluna no dataframe

In [37]:
df

               2002      2020      2019      2006       nnt
BRASIL     0.516399  0.570668  0.028474  0.171522  0.687920
ALEMANHA   0.685277  0.833897  0.306966  0.893613  1.578890
FRANÇA     0.721544  0.189939  0.554228  0.352132  1.073676
ESPANHA    0.181892  0.785602  0.965483  0.232354  0.414246
ARGENTINA  0.083561  0.603548  0.728993  0.276239  0.359800

In [38]:
df.drop('nnt', axis= 1)
# exclui a coluna nnt 1 por conta de ser coluna

               2002      2020      2019      2006
BRASIL     0.516399  0.570668  0.028474  0.171522
ALEMANHA   0.685277  0.833897  0.306966  0.893613
FRANÇA     0.721544  0.189939  0.554228  0.352132
ESPANHA    0.181892  0.785602  0.965483  0.232354
ARGENTINA  0.083561  0.603548  0.728993  0.276239

In [39]:
df
# nao atribuiu ao dataframe original o drop

               2002      2020      2019      2006       nnt
BRASIL     0.516399  0.570668  0.028474  0.171522  0.687920
ALEMANHA   0.685277  0.833897  0.306966  0.893613  1.578890
FRANÇA     0.721544  0.189939  0.554228  0.352132  1.073676
ESPANHA    0.181892  0.785602  0.965483  0.232354  0.414246
ARGENTINA  0.083561  0.603548  0.728993  0.276239  0.359800

In [40]:
df.drop('nnt', axis= 1, inplace=True)
# utilizando o parametro inplace a alteração sera feita direto no dataframe

In [41]:
df

               2002      2020      2019      2006
BRASIL     0.516399  0.570668  0.028474  0.171522
ALEMANHA   0.685277  0.833897  0.306966  0.893613
FRANÇA     0.721544  0.189939  0.554228  0.352132
ESPANHA    0.181892  0.785602  0.965483  0.232354
ARGENTINA  0.083561  0.603548  0.728993  0.276239