In [2]:
import numpy as np
import pandas as pd

In [5]:
f = {'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}
# cria um dicionario com numeros e tambem NaN

In [6]:
df = pd.DataFrame(f)

In [7]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [8]:
df.dropna()
# exclui todas as linhas que tenham Nan

     A    B  C
0  1.0  5.0  1

In [9]:
df['A'].fillna(value=df['A'].mean())
# preenche todos os Nan de A com  media da coluna A

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [11]:
df.fillna(method='ffill')
# preenche todos os Nan com o valor anterior da coluna

C:\Users\Matheus\AppData\Local\Temp\ipykernel_16868\4252194000.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

     A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  2.0  5.0  3