In [1]:
import pandas as pd
import numpy as np

In [ ]:
out = ['1a', '1a', '1a','2b', '2b', '2b']
inn = [1,2,3,1,2,3]
#h_index = list(zip(out,inn))
#h_index  =pd.MultiIndex.from_tuples(h_index)

In [3]:
out

['1a', '1a', '1a', '2b', '2b', '2b']

In [4]:
inn

[1, 2, 3, 1, 2, 3]

In [ ]:
h_index = list(zip(out,inn))
# cria uma lista de tuplas tendo cada tupla com um elemento de out e um  inn

In [7]:
h_index

[('1a', 1), ('1a', 2), ('1a', 3), ('2b', 1), ('2b', 2), ('2b', 3)]

In [ ]:
h_index = pd.MultiIndex.from_tuples(h_index)
# cria um MultiIndex a partir da lista de tuplas

In [9]:
h_index

MultiIndex([('1a', 1),
            ('1a', 2),
            ('1a', 3),
            ('2b', 1),
            ('2b', 2),
            ('2b', 3)],
           )

In [ ]:
df = pd.DataFrame(np.random.randn(6,2), index=h_index, columns=['A','B'])
# cria um df separado por grupo e subgrupo

In [14]:
df

             A         B
1a 1  1.350630  0.524634
   2 -0.541110 -0.898125
   3  0.215338 -0.009418
2b 1 -0.581319 -0.230430
   2  0.586017  0.705502
   3  0.090107  0.287390

In [ ]:
df.index.names = ['grp', 'int']
# atribui nomes aos niveis de indice

In [16]:
df

                A         B
grp int
1a  1    1.350630  0.524634
    2   -0.541110 -0.898125
    3    0.215338 -0.009418
2b  1   -0.581319 -0.230430
    2    0.586017  0.705502
    3    0.090107  0.287390

In [ ]:
df.xs(1, level='int')
# seleciona todas as linhas do df que tem o valor 1 no nivel int do indice

            A         B
grp
1a   1.350630  0.524634
2b  -0.581319 -0.230430