In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'Empresa': ['NVDA', 'NVDA', 'NVDA', 'TSLA', 'TSLA', 'TSLA', 'AAPL', 'AAPL', 'AAPL', 'NFLX', 'NFLX', 'NFLX'],
    'Nome': ['Lucas', 'Fernanda', 'Ricardo', 'Beatriz', 'Thiago', 'Camila', 'Rafael', 'Juliana', 'Pedro', 'Mariana', 'Felipe', 'Isabela'],
    'Venda': [200, 120, 310, 340, 124, 275, 243, 350, 180, 410, 95, 260]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

   Empresa      Nome  Venda
0     NVDA     Lucas    200
1     NVDA  Fernanda    120
2     NVDA   Ricardo    310
3     TSLA   Beatriz    340
4     TSLA    Thiago    124
5     TSLA    Camila    275
6     AAPL    Rafael    243
7     AAPL   Juliana    350
8     AAPL     Pedro    180
9     NFLX   Mariana    410
10    NFLX    Felipe     95
11    NFLX   Isabela    260

In [ ]:
grp = df.groupby('Empresa')
# agrupa os dados por Empresa

In [ ]:
grp.sum()
# soma os valores de Venda por Empresa

                         Nome  Venda
Empresa
AAPL       RafaelJulianaPedro    773
NFLX     MarianaFelipeIsabela    765
NVDA     LucasFernandaRicardo    630
TSLA      BeatrizThiagoCamila    739

In [ ]:
grp = df.groupby('Nome')
# agrupa por Nome

In [11]:
grp.sum()

         Empresa  Venda
Nome
Beatriz     TSLA    340
Camila      TSLA    275
Felipe      NFLX     95
Fernanda    NVDA    120
Isabela     NFLX    260
Juliana     AAPL    350
Lucas       NVDA    200
Mariana     NFLX    410
Pedro       AAPL    180
Rafael      AAPL    243
Ricardo     NVDA    310
Thiago      TSLA    124