In [1]:
import numpy as np
import pandas as pd

In [ ]:
d = {'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}
# cria um dicionario comm numeros e NaN

In [ ]:
df = pd.DataFrame(d)
# transforma o dict em um dataframe pandas

In [5]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.dropna(thresh=2)
# dropna exclui todas as linhas com NaN, mas com thresh caada linha preciisa de pelo menos 2 Nan para ser excluida

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [ ]:
df['A'].fillna(value=df['A'].mean())
# preenche na coluna A os NaN com a media de A

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [12]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.fillna(method='ffill')
# preenche os NAn com os valores proximos, no exemplo foi com o numero anterior

C:\Users\Matheus\AppData\Local\Temp\ipykernel_26416\1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

     A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  2.0  5.0  3