In [1]:
import numpy as np
import pandas as pd

In [2]:
from numpy.random import randn
np.random.seed(101)

In [ ]:
df = pd.DataFrame(randn(5,4), index= 'A B C D E'. split(), columns='W X Y Z'.split())
# cria um dataframe com 5 linhas e 4 colunas com numeros aleatorios

In [4]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [6]:
bol = df > 0

In [7]:
bol

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [ ]:
df[bol]
# todos os numeros negativos, ou melhor False viraram Nan

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df[df['W'] > 0]
# mostra os indices de W que sao maiores que 0

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df[df['W'] > 0]['Y']
# mostrar os numeros de Y inde os indices de W sao maiores que 0

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [ ]:
df[(df['W']>0) & (df['Y']>1)]
# mostra a linha onde W e maior que 0 e Y maior que 1, nao seu usa and pois nao pose ser feita comparação de dataframes com tal

          W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [13]:
df[(df['W']>0) | (df['Y']>1)]
# mostra a linha onde W e maior que 0 ou Y maior que 1

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df.reset_index(inplace=True)
# coloca um indice na tabela

In [16]:
df

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [17]:
col = 'RS RJ SP AM SC'.split()

In [18]:
col

['RS', 'RJ', 'SP', 'AM', 'SC']

In [ ]:
df['Estado'] = col
# nova coluna adicionada ao datframe

In [20]:
df

  index         W         X         Y         Z Estado
0     A  2.706850  0.628133  0.907969  0.503826     RS
1     B  0.651118 -0.319318 -0.848077  0.605965     RJ
2     C -2.018168  0.740122  0.528813 -0.589001     SP
3     D  0.188695 -0.758872 -0.933237  0.955057     AM
4     E  0.190794  1.978757  2.605967  0.683509     SC

In [ ]:
df.set_index('Estado', inplace=True)
# coloca a coluna Estado como index do dataframe

In [23]:
df

       index         W         X         Y         Z
Estado
RS         A  2.706850  0.628133  0.907969  0.503826
RJ         B  0.651118 -0.319318 -0.848077  0.605965
SP         C -2.018168  0.740122  0.528813 -0.589001
AM         D  0.188695 -0.758872 -0.933237  0.955057
SC         E  0.190794  1.978757  2.605967  0.683509