In [1]:
import numpy as np
import pandas as pd

In [ ]:
outside = ['G1', 'G1', 'G1','G2', 'G2', 'G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index  =pd.MultiIndex.from_tuples(hier_index)

In [3]:
outside

['G1', 'G1', 'G1', 'G2', 'G2', 'G2']

In [4]:
inside

[1, 2, 3, 1, 2, 3]

In [ ]:
hier_index = list(zip(outside,inside))
# cria uma lista de tuplas onde ccada tula possui um elemento de outside e um de inside'

In [6]:
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [ ]:
hier_index  =pd.MultiIndex.from_tuples(hier_index)  
# cria um MultiIndex a partir da lista de tuplas

In [8]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [ ]:
df = pd.DataFrame(np.random.randn(6,2), index=hier_index, columns = ['A', 'B'])
# cria um dataframe com indice separado pelo grupo G1 e G2, com numeros sorteados

In [14]:
df

             A         B
G1 1  0.011922 -0.774046
   2 -1.323663  0.879325
   3 -0.077624 -0.497370
G2 1 -0.315439  0.727874
   2  0.550354  0.420828
   3 -0.536780 -0.479653

In [ ]:
df.index.names = ['Grupo', 'Numero']
# nomeia os indices Grupo e Numero

In [16]:
df

                     A         B
Grupo Numero
G1    1       0.011922 -0.774046
      2      -1.323663  0.879325
      3      -0.077624 -0.497370
G2    1      -0.315439  0.727874
      2       0.550354  0.420828
      3      -0.536780 -0.479653

In [ ]:
df.xs(1, level='Numero')
# pega diretamente pelo numero e nao precisa passar pelo grupo

              A         B
Grupo
G1     0.011922 -0.774046
G2    -0.315439  0.727874