In [2]:
import pandas as pd
import numpy as np

In [ ]:
np.random.seed(101)
# cria valores aleatorios universais, que podem ser vistos igualmente

In [7]:
df = pd.DataFrame(np.random.randn(5,4), index = ' A B C D E'.split(), columns = 'W X Y Z'.split())
# faz um dataframe(tabela), com numeros sorteados usando rand n de 5 linhas e 4 colunas, o spli() separa pelos espaços as letras para assim coloca-las nas linhas e nas colunas

In [8]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [11]:
df['new'] = df['W'] + df['X']
# soma as colunas w e x e coloca elas em uma nova coluna no dataframe

In [12]:
df

          W         X         Y         Z       new
A  0.302665  1.693723 -1.706086 -1.159119  1.996388
B -0.134841  0.390528  0.166905  0.184502  0.255687
C  0.807706  0.072960  0.638787  0.329646  0.880666
D -0.497104 -0.754070 -0.943406  0.484752 -1.251174
E -0.116773  1.901755  0.238127  1.996652  1.784981

In [ ]:
df.drop('new', axis= 1)
# exclui a coluna new, o axis selecio a coluna por conta do 1, se for 0 e o indice de linha

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [ ]:
df
# nao atribuiu ao dataframe original o drop

          W         X         Y         Z       new
A  0.302665  1.693723 -1.706086 -1.159119  1.996388
B -0.134841  0.390528  0.166905  0.184502  0.255687
C  0.807706  0.072960  0.638787  0.329646  0.880666
D -0.497104 -0.754070 -0.943406  0.484752 -1.251174
E -0.116773  1.901755  0.238127  1.996652  1.784981

In [16]:
df.drop('new', axis= 1, inplace=True)
# utilizando o parametro inplace a alteração sera feita direto no dataframe