In [6]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc', 'def', 'ghi', 'xyz']})

In [4]:
df.head()
# mostra linhas inicais do dataframe o padrao e 5

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [8]:
df['col2'].unique()
# pega os valores unicos, descartando duplicadas

array([444, 555, 666])

In [ ]:
len(df['col2'].unique())
# mostra quantos valores da coluna 2 sao unicos

3

In [ ]:
df['col2'].nunique()
# mesma coisa que a celula de cima

3

In [12]:
df['col2'].value_counts()
# mostra quantos valores cada valor tem

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [ ]:
df[df['col1']>2]
# mostra oela coluna 1 quais valores sao maiores que sao maiores que 2

   col1  col2 col3
2     3   666  ghi
3     4   444  xyz

In [16]:
df[(df['col1']>2)& (df['col2']==444)]
# retorna a linha onde col1 e maior que 2 e col2 e = 444

   col1  col2 col3
3     4   444  xyz

In [22]:
def vezes2(x):
    return x*2

In [24]:
df['col1'].apply(vezes2)
# aplica a funcao para cada elemento da coluna 1

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [25]:
df['col1'].apply(lambda x: x*2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [ ]:
del df['col2']
# deleta a coluna 2 do dataframe

In [27]:
df

   col1 col3
0     1  abc
1     2  def
2     3  ghi
3     4  xyz

In [ ]:
df.columns
# mostra as colunas do Dataframe

Index(['col1', 'col3'], dtype='object')

In [34]:
df.sort_values(by='col3', inplace=True)
# ordena a coluna 3

In [35]:
df

   col1 col3
0     1  abc
1     2  def
2     3  ghi
3     4  xyz

In [ ]:
df.isnull()
# mostra as colunas com elementos nullos

    col1   col3
0  False  False
1  False  False
2  False  False
3  False  False

In [37]:
df = pd.DataFrame({
    'col1': [1, 2, 3, np.nan],
    'col2': [np.nan, 555, 666, 444],
    'col3': ['abc', 'def', 'ghi', 'xyz']
})

In [38]:
df.head()

   col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [ ]:
df['col1'].fillna(value=df['col1'].mean())
# preenche os vslores NaN com a media da coluna 1

0    1.0
1    2.0
2    3.0
3    2.0
Name: col1, dtype: float64

In [42]:
data = {
    'A': ['foo', 'foo', 'foo', 'bar', 'bar', 'bar'],
    'B': ['one', 'one', 'two', 'two', 'one', 'one'],
    'C': ['x', 'y', 'x', 'y', 'x', 'y'],
    'D': [1, 3, 2, 5, 4, 1]
}

df = pd.DataFrame(data)

In [43]:
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [ ]:
df.pivot_table(values='D', index=['A', 'B'], columns=['C'])
# agrupa as linhas por A e B e transforma C em colunas e preenche com os valores de D

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN